### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by PatentOwl**
Its just for the good.

### CODE REVIEW

**Comment by miqumi** [comment]
What
thats not very related
its very specific and ISNT written in clear language.
i might rewrite it if you can tell me what the text is intended for

**Comment by PatentOwl** [comment]
Ok so basically its meant to say that its possible to lose your os. I
installed the programm ran it and it restarted. With an error that the os
was not found. I was eventually able to restore it tho. But i wanted to
point that out cuz some people may have the same issue and dont know what
to do. I basically wanted to warn them that this is indeed possible.

Shrey ***@***.***> schrieb am Mo., 24. Juli 2023, 14:07:

**Comment by miqumi** [comment]
its definitely not related to mcrack

**Comment by QwertyTheCoder** [comment]
> its definitely not related to mcrack

Yeah

**Pull request closed without merging**
